#!/usr/bin/env bash

if [ "$1" = "" ]; then
    echo "Use: $0 file"
else
    cat $1 |
	awk -f foo.awk            |
	sed "/^#/! s/\'/\\\'/g"   | # Escape '
	sed '/^#/! s/\$/\\\$/g'   | # Escape $
	sed '/^#/! s/\!/\\\!/g'   | # Escape !
	sed '/^#/! s/\\/\\\\/g'   | # Escape \
	sed "/^#/! s/^/echo \"/g" | # Add echo commands to non-commented lines
	sed "/^#/! s/$/\"/g"      | # Add trailing double-quotes
	sed "s/^#//g"             | # Remove the comment characters themselves
        bash
fi

